POST localhost:8081/users/password/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjAxMjA3Nzd9.hsxGC6dXWeNMnLbR3OWkQqnZom-t2bjfszdPgIj_l0fKR2_Wr65nHhf_Jfyf2sERuPEmmXB5fFNNxYSvNo9OYQ
Content-Type: application/json;

{
	"password" : "test1"
}