POST localhost:8081/contests/start
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLQUtBTzI0NzI3NTc2NDciLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY1NTQ0NTQ3fQ.CRVL28Mb4dxATE-l4-8Pmy-TZTLz56ZG8LMqg0i-C0GxYbDXlWJ3GvNSjsfaeOJDa18ye54hn0sAjWj8WlxTjw
Content-Type: application/json;

{
  "problemSetId" : 1
}