POST localhost:8081/code/save
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0amRhaHIyNSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NTkzNjE2NzN9.I5IHJHKUbbkl3QopP3yycASP76ENsXtFr-9tijufwMIXdRpv0Q9EQHR1wdPY06cSgG-F1kfkE4KBllnGNCRl_w
Content-Type: application/json;

{
  "code" : "TEST",
  "contestId" : 244,
  "problemId" : 200,
  "language" : "c++17"
}