POST localhost:8081/contests/start
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dHR0IiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2ODIzMDMxN30.hPsUoSBYNsezzc9JLNyReVUi5jnny9YTVFFt8xrUTUWRCmi7HHAgjL-eiXv0Yt87Xo-Ny_HA1UZu8K_J4tAr6g
Content-Type: application/json;

{
  "problemSetId" : 1
}