POST localhost:8081/submit
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NTk1ODE3NTV9.xMhBKMKbISZaX8VXUHOhEuiVlcpLWgKzLCqXT-_LnfhXantD5va9zlGE582jbxA9zGQjxpIdxLJO-aWiEXZr_A
Content-Type: application/json

{
  "problemId": 1,
  "input": "1 4",
  "contestId" : -1,
  "testMode" : true,
  "language": "c++17",
  "source": "#include <iostream>\nusing namespace std;\nint main(){int a, b; cin>>a>>b; cout<<a+b;}"
}