POST 43.200.180.31:8081/users/password/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0amRhaHIyNSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjAxNzMxMjB9.hb8vGntLRxzWX3QDAs6os7BsB0ZMCof2Tzho93Q70ViOgFbVujrQk55kHwQqqOnA0vOSNuhnPC11et8h4IynCw
Content-Type: application/json;

{
	"password" : "tjdahr25"
}