POST https://api.codemap.ai/users/kakao/interlock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2ODUxNjY0M30.9CREyP2cwsZw53MCow-BRrVjgjHED6K0ZXzBghiZCS5Ql08pBWuk_nCoU0LOR0mDZDjMX3gmCds2o_aB6Mhlog
Content-Type: application/json;

{
  "id" : 2472757647
}