POST localhost:8081/contests/start
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0amRhaHIyNSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NTkxNTQ3MjJ9.Nlz6uTU1ne41e0Eyauz4En6fF0DfqrlDelBX9k6DtWxuJoqceZsEqBUJuolSCUlvkSc3isAQtj_bnkRe-ZmKrA
Content-Type: application/json;

{
  "problemSetId" : 1
}