POST https://api.codemap.ai/users/kakao/interlock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dHR0IiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2ODUwNjQ3NX0.HYtrCFxi45rhzjXTOEpMEGTK_Zhn23dP8qB4RQG_Z6-Hr-CBxIvJPMyGz8ofBqKJQR1HsMmPiJUjK2NXAXgd3A
Content-Type: application/json;

{
  "id" : 2472757647
}