GET https://api.codemap.ai/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2ODUxMTI0MH0.zdK3IMGvBbDmrx1KCHaJ44z9-XDPx_P4Z73MjnwWUbtPBy1kInrpgEnmolhJKQx2ia8Ps-C3pDl1pgdW4KpHQg