GET localhost:8081/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2ODUxMTEyMn0.nVK-pt_hQoiYmqcg2bNYIuhlue9ypQ1JUG9lJUjOQu84kKf_eh6gms2vXkJHBRB_uKIZf9b1SOKgLq3soCZaBQ
